version: '3.3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:8080
      - 8000:8000
    restart: on-failure
    networks:
      - main

networks:
  main:
